### ISSUE TITLE
SwiftOracle package works in Linux but not in MacOS.

### ISSUE THREAD

**Issue by bhregmi** [iliasaz/cocilib#1]
I checked out you SwiftOracle package in my project , and i was able to use it in Linux successfully but it throws  error  while using in MacOS esp in Connection.swift file -----> ( public func open() throws {
        connection = OCI_ConnectionCreate(conn_info.service_name, conn_info.user, conn_info.pwd, UInt32(OCI_SESSION_DEFAULT));
    })
Would you please look into this issue.

**Comment by iliasaz** [comment]
What error are you getting on Mac?
Did you install OCILIB and Oracle instant client on Mac?

**Comment by bhregmi** [comment]
Yes i have installed OCILIB and Oracle Instant client. And the error is :
<img width="1027" alt="Screen Shot 2021-10-18 at 4 43 26 PM" src="https://user-images.githubusercontent.com/66964165/137718548-80dcfb75-31b3-4e54-9141-12fb0aa38c97.png">

Seems like problem with opening connection. Does it work in your mac ?

**Comment by iliasaz** [comment]
It does work fine on my Mac in a strand-alone application. However, I see from your call stack that you're calling it from a HTTP handler, which is presumably multithreaded. By default, the connection we create using Connection object via OCILIB is not thread safe. This is why I introduced the connection pooling in the ConnectionPool class. But the version currently checked in is still not fully thread safe, I'll check in a newer version in the next 1-2 days.
Are you using Vapor by any chance? If so, I have an example of integrating SwiftOracle with vapor4 in a thread safe manner that has worked for me on both Linux and Mac. I'll check it in in a couple of days, too.
Thanks!

**Comment by iliasaz** [comment]
Please pull from the master branch (or use [this commit](https://github.com/iliasaz/SwiftOracle/commit/4b21318e9e6db689a31a11f1b073b2a7754aa3e5))

This should work in a multithreaded environment on both Mac and Linux. Please use the ConnectionPool implementation, not the original Connection. 

I'll post a Vapor example a bit later.

**Comment by iliasaz** [comment]
Added [a sample application](https://github.com/iliasaz/vapor-oracle) showing the use of SwiftOracle with Vapor 4.

**Comment by bhregmi** [comment]
Thanks, it worked after reinstalling ocilib without CFLAGS="-O2 -m64" , I don't know why it didn't work earlier.   I am developing a simple application in vapor and your sample saved my day. 
I guess, the ocilib  package needs to be updated too  as it shows this warning. "system packages are deprecated; use system library targets instead" . In the future version it may create problem.

**Comment by iliasaz** [comment]
Yes, I'll change it to system library in the next release. 
Please feel free to star my repo if you liked it 😄

**Comment by bhregmi** [comment]
BTW did you get a chance to check if it works with unicode characters in mac ( works fine in ubuntu though) ?
 
I configured OCILIB with ( so as to support unicode characters) : 
./configure --with-oracle-home=$ORACLE_HOME --with-oracle-lib-path=$ORACLE_HOME --with-oracle-headers-path=$ORACLE_HOME/sdk/include --disable-dependency-tracking  --with-oracle-charset=wide CFLAGS="-O2 -m64"

and couldn't display unicode characters ( only ANSI characters ).

**Comment by iliasaz** [comment]
According to [OCILIB documentation](http://vrogier.github.io/ocilib/doc/html/group___ocilib_c_api_supported_charsets.html), UTF8 is supported with default with OCI_CHARSET_ANSI, but you may need to set NLS_LANG environment variable to a valid UTF8-supporting value. 
For example, I compiled OCILIB with default charset settings on my Mac, set NLS_LANG=RUSSIAN_RUSSIA.AL32UTF8, and I can see both Cyrillic characters and emojis.

In Xcode:
![Screen Shot 2021-10-23 at 1 52 37 PM](https://user-images.githubusercontent.com/24770194/138571264-8acd1d32-30be-4ef0-9d74-0f6d37d14690.png)
.

In my MacOS app:
![Screen Shot 2021-10-23 at 1 54 36 PM](https://user-images.githubusercontent.com/24770194/138571296-892a0c59-75b2-444a-8344-566453d0ec2c.png)
